#Jedis
redis:
  jedis:
    database: 0
    host: 127.0.0.1
    password: 545825
    pool:
      max-active: 200
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 6000

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  http:
    encoding:
      charset: utf-8
      enabled: true
  #数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yyjh_datasource?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 545825
    # HKCP
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
      type: com.zaxxer.hikari.HikariDataSource

#Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.group_six.data-service

#日志文件
logging:
  file: yyjh-datasource.log
  path: /var/log/
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'

#文件目录
file:
  upload:
    path:
      datasource:
        csv: /yyjhFiles/datasource/csv
        excel: /yyjhFiles/datasource/excel